apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: evaluation-service
  labels:
    app: evaluation-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
        tier: backend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: evaluation-service
          image: 929265854968.dkr.ecr.us-east-1.amazonaws.com/togglemaster/evaluation-service:1ae6279a7e024f2662378d68f1b7720f15f33db1
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
              protocol: TCP
          envFrom:
            - secretRef:
                name: evaluation-service-secrets
            - secretRef:
                name: aws-credentials
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.observability.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_SERVICE_NAME
              value: "evaluation-service"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=togglemaster,deployment.environment=production"
            - name: OTEL_TRACES_SAMPLER
              value: "parentbased_always_on"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
