apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: analytics-service
  labels:
    app: analytics-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
        tier: backend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: analytics-service
          image: 929265854968.dkr.ecr.us-east-1.amazonaws.com/togglemaster/analytics-service:49332070452614842a58f23b6420ff30ede666b8
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
              protocol: TCP
          envFrom:
            - secretRef:
                name: analytics-service-secrets
            - secretRef:
                name: aws-credentials
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.observability.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_SERVICE_NAME
              value: "analytics-service"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=togglemaster,deployment.environment=production"
            - name: OTEL_TRACES_SAMPLER
              value: "parentbased_always_on"
            - name: OTEL_PYTHON_LOG_CORRELATION
              value: "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
